<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="5438" started-at="2021-04-01T18:21:41 EDT" finished-at="2021-04-01T18:21:47 EDT">
    <groups>
    </groups>
    <test name="DataDrivenFramework" duration-ms="5438" started-at="2021-04-01T18:21:41 EDT" finished-at="2021-04-01T18:21:47 EDT">
      <class name="org.example.testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.example.testcases.BankManagerLoginTest@561868a0]" name="setUp" is-config="true" duration-ms="4543" started-at="2021-04-01T18:21:37 EDT" finished-at="2021-04-01T18:21:41 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginAsManager()[pri:0, instance:org.example.testcases.BankManagerLoginTest@561868a0]" name="loginAsManager" duration-ms="5412" started-at="2021-04-01T18:21:41 EDT" finished-at="2021-04-01T18:21:47 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at org.example.testcases.BankManagerLoginTest.loginAsManager(BankManagerLoginTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsManager -->
        <test-method status="PASS" signature="teatDown()[pri:0, instance:org.example.testcases.BankManagerLoginTest@561868a0]" name="teatDown" is-config="true" duration-ms="1109" started-at="2021-04-01T18:21:47 EDT" finished-at="2021-04-01T18:21:48 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatDown -->
      </class> <!-- org.example.testcases.BankManagerLoginTest -->
    </test> <!-- DataDrivenFramework -->
  </suite> <!-- Default Suite -->
</testng-results>
